"""Import the user-supplied Maison des Quinze ZIP without running its scripts.

Usage: python3 scripts/import-main-villa.py /path/to/Complete.zip
Preserves metre coordinates and all triangles; only batches and buffers change.
"""
import hashlib
import json
from pathlib import Path
import struct
import subprocess
import sys
import tempfile
import zipfile

ROOT = Path(__file__).resolve().parents[1]
PREFIX = 'Cochonnet_Maison_des_Quinze/'
with zipfile.ZipFile(sys.argv[1]) as archive:
    source = archive.read(PREFIX + 'Cochonnet_Maison_des_Quinze_FULL.glb')
    manifest = json.loads(archive.read(PREFIX + 'integration_manifest.json'))
    proxies = json.loads(archive.read(PREFIX + 'collision_proxies.json'))['static_aabbs']
    guards = json.loads(archive.read(PREFIX + 'roof_guard_barriers.json'))['segments']
    expected = archive.read(PREFIX + 'SHA256SUMS.txt').decode()
    source_hash = hashlib.sha256(source).hexdigest()
    if source_hash not in expected:
        raise ValueError('Full GLB does not match the supplied checksum list')
    evidence = ROOT / 'art/resort/maison-des-quinze'
    evidence.mkdir(parents=True, exist_ok=True)
    for name in ['integration_manifest.json', 'collision_proxies.json', 'roof_guard_barriers.json']:
        (evidence / name).write_bytes(archive.read(PREFIX + name))

output = ROOT / 'public/models/resort/villa.glb'
with tempfile.TemporaryDirectory() as scratch:
    raw = Path(scratch) / 'villa.glb'
    raw.write_bytes(source)
    subprocess.run([str(ROOT / 'node_modules/.bin/gltfpack'), '-i', str(raw),
                    '-o', str(output), '-c', '-vp', '16', '-vn', '10'], check=True)

data = {
    'mount': manifest['runtime_mount']['position'],
    'floorElevations': manifest['floor_elevations'],
    'counts': manifest['counts'],
    'upperRectangles': manifest['upper_floor_local_three_rectangles'],
    'upperVoids': manifest['upper_voids_local_three'],
    'stair': manifest['stair'],
    'roof': manifest['roof_garden'],
    'rooms': manifest['rooms'],
    'portals': manifest['portals'],
    'proxies': [[p['name'], p['role'],
                 [round(x, 5) for x in p['aabb_local_three_min']],
                 [round(x, 5) for x in p['aabb_local_three_max']]] for p in proxies],
    'guards': [[g['id'], g['start_local_three'], g['end_local_three'],
                g['suggested_horizontal_thickness_m']] for g in guards]
}
runtime = ROOT / 'src/villa-map/main-villa-data.js'
runtime.write_text('// Generated by scripts/import-main-villa.py. Coordinates are villa-local Y-up.\n'
                   + 'export const MAIN_VILLA_DATA = ' + json.dumps(data, indent=2) + ';\n')
packed = output.read_bytes()
glb = json.loads(packed[20:20 + struct.unpack_from('<I', packed, 12)[0]])
report = {
    'source': 'Cochonnet_Villa_Maison_des_Quinze_Complete.zip',
    'source_glb_sha256': source_hash,
    'runtime_glb_sha256': hashlib.sha256(packed).hexdigest(),
    'source_triangles': manifest['exports']['Cochonnet_Maison_des_Quinze_FULL.glb']['triangles'],
    'runtime_triangles': sum(glb['accessors'][p['indices']]['count'] // 3
                             for m in glb['meshes'] for p in m['primitives']),
    'runtime_batches': sum(len(m['primitives']) for m in glb['meshes']),
    'runtime_bytes': len(packed),
    'command': 'gltfpack -c -vp 16 -vn 10 (no simplification)',
    'mount': data['mount'],
    'scale': [1, 1, 1],
    'textures': 'Shared pure-colour PBR; no textures or baked AO',
}
(evidence / 'import-report.json').write_text(json.dumps(report, indent=2) + '\n')
print(json.dumps(report, indent=2))
