// SEO helpers shared by the Astro pages (through components/SeoHead.astro),
// the /sitemap.xml endpoint, and the node test suite. Node-pure: no
// window/document access. `astro.config.mjs` `site` mirrors SITE_URL — pass
// `Astro.site` in where available so the two cannot drift silently.

import { isValidNoteDate, noteArtDimensions, noteExcerpt } from "./render-notes.js";

export const SITE_URL = "https://www.cochonnetvilla.ca";
export const SITE_NAME = "Cochonnet Villa";
export const SITE_NAME_ZH = "猪猪山庄";

export const NOTES_TITLE = "猪猪小记 | 猪猪山庄";
export const NOTES_DESCRIPTION = "猪猪山庄的随笔小本子：日常、小猪们的新鲜事，和一些突然想说的话。";

export const VILLA_MAP_TITLE = "猪猪山庄实景地图 | Cochonnet Villa";
export const VILLA_MAP_DESCRIPTION =
  "在浏览器里逛一逛猪猪山庄的 3D 实景：温泉、蘑菇屋、主厅，还有 15 只小猪的家。Explore the 3D grounds of Cochonnet Villa: hot springs, the mushroom house and the main hall.";

// Default share card (1200×630), generated by scripts/generate-og-cover.py.
export const DEFAULT_SHARE_IMAGE = Object.freeze({
  path: "/assets/og-cover.jpg",
  width: 1200,
  height: 630,
  alt: "猪猪山庄 Cochonnet Villa：15 只快乐小猪的家"
});

const SCHEMA_CONTEXT = "https://schema.org";

function siteOrigin(site) {
  return String(site ?? SITE_URL).replace(/\/+$/, "");
}

// Pages build as directories (/notes/index.html), so a page's canonical form
// carries a trailing slash; file-like paths (sitemap.xml, images) keep theirs.
export function normalizePath(pathname) {
  let path = String(pathname ?? "/").trim();

  if (!path.startsWith("/")) {
    path = `/${path}`;
  }

  const lastSegment = path.slice(path.lastIndexOf("/") + 1);

  if (!path.endsWith("/") && !lastSegment.includes(".")) {
    path = `${path}/`;
  }

  return path;
}

export function absoluteUrl(pathOrUrl, site = SITE_URL) {
  const value = String(pathOrUrl ?? "").trim();

  if (/^https?:\/\//i.test(value)) {
    return value;
  }

  return `${siteOrigin(site)}${normalizePath(value)}`;
}

export function shareImage(image = DEFAULT_SHARE_IMAGE, site = SITE_URL) {
  return {
    url: absoluteUrl(image.path ?? image.url, site),
    ...(image.width ? { width: image.width } : {}),
    ...(image.height ? { height: image.height } : {}),
    ...(image.alt ? { alt: image.alt } : {})
  };
}

// Note art is the note's own share image; a note without art (not yet
// processed by the art workflow) shares the site card instead.
export function noteShareImage(note, site = SITE_URL) {
  if (!note?.image) {
    return shareImage(DEFAULT_SHARE_IMAGE, site);
  }

  const size = noteArtDimensions(note.image) ?? {};

  return shareImage(
    {
      path: note.image,
      ...size,
      alt: `《${note.title}》的小猪漫画配图`
    },
    site
  );
}

export function notePath(note) {
  return `/notes/${note.slug}/`;
}

// A note stores only the diarist's calendar day, but structured data wants a
// zoned datetime (Rich Results flags a bare date). Publish local noon in the
// villa's timezone: it reads as the same calendar day in every reader's zone,
// DST or not.
export const NOTE_TIMEZONE = "America/Toronto";

export function noteDateTime(date, timeZone = NOTE_TIMEZONE) {
  if (!isValidNoteDate(date)) {
    return "";
  }

  const offset = new Intl.DateTimeFormat("en-US", { timeZone, timeZoneName: "longOffset" })
    .formatToParts(new Date(`${date}T12:00:00Z`))
    .find((part) => part.type === "timeZoneName").value;

  return `${date}T12:00:00${offset === "GMT" ? "+00:00" : offset.slice(3)}`;
}

export function buildSitemapEntries(notes, { site = SITE_URL } = {}) {
  const list = Array.isArray(notes) ? notes : [];
  const newest = list
    .map((note) => note.date)
    .filter(Boolean)
    .sort()
    .at(-1);

  const entry = (path, lastmod) => ({
    loc: absoluteUrl(path, site),
    ...(lastmod ? { lastmod } : {})
  });

  return [
    entry("/", newest),
    entry("/notes/", newest),
    ...list.map((note) => entry(notePath(note), note.date)),
    entry("/villa-map/")
  ];
}

function escapeXml(value) {
  return String(value ?? "").replace(/[&<>"']/g, (character) => {
    switch (character) {
      case "&":
        return "&amp;";
      case "<":
        return "&lt;";
      case ">":
        return "&gt;";
      case '"':
        return "&quot;";
      case "'":
        return "&apos;";
      default:
        return character;
    }
  });
}

export function renderSitemapXml(entries) {
  const urls = (Array.isArray(entries) ? entries : [])
    .map((entry) => {
      const lastmod = entry.lastmod ? `\n    <lastmod>${escapeXml(entry.lastmod)}</lastmod>` : "";
      return `  <url>\n    <loc>${escapeXml(entry.loc)}</loc>${lastmod}\n  </url>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}

export function renderRobotsTxt({ site = SITE_URL } = {}) {
  // /admin/ is kept crawlable on purpose: its pages carry
  // <meta name="robots" content="noindex">, and a robots.txt Disallow would
  // hide that directive from the crawler (the URL could then be indexed
  // title-less from the footer link).
  return [
    "User-agent: *",
    "Allow: /",
    "",
    `Sitemap: ${absoluteUrl("/sitemap.xml", site)}`,
    ""
  ].join("\n");
}

// JSON-LD ------------------------------------------------------------------

function organization(site) {
  return {
    "@type": "Organization",
    name: `${SITE_NAME_ZH} ${SITE_NAME}`,
    url: absoluteUrl("/", site),
    logo: shareImage(DEFAULT_SHARE_IMAGE, site).url
  };
}

export function websiteJsonLd({ site = SITE_URL, description = "" } = {}) {
  return {
    "@context": SCHEMA_CONTEXT,
    "@type": "WebSite",
    name: SITE_NAME,
    alternateName: SITE_NAME_ZH,
    url: absoluteUrl("/", site),
    ...(description ? { description } : {}),
    inLanguage: ["en", "zh-Hans"]
  };
}

export function webPageJsonLd({ site = SITE_URL, path, name, description, inLanguage = "zh-Hans" }) {
  return {
    "@context": SCHEMA_CONTEXT,
    "@type": "WebPage",
    name,
    url: absoluteUrl(path, site),
    ...(description ? { description } : {}),
    inLanguage,
    isPartOf: { "@type": "WebSite", name: SITE_NAME, url: absoluteUrl("/", site) }
  };
}

export function blogPostingJsonLd(note, { site = SITE_URL, context = true } = {}) {
  const url = absoluteUrl(notePath(note), site);

  return {
    ...(context ? { "@context": SCHEMA_CONTEXT } : {}),
    "@type": "BlogPosting",
    headline: note.title,
    url,
    mainEntityOfPage: url,
    ...(note.date ? { datePublished: noteDateTime(note.date) } : {}),
    description: noteExcerpt(note.body, 120),
    image: [noteShareImage(note, site).url],
    inLanguage: "zh-Hans",
    author: organization(site),
    publisher: organization(site)
  };
}

export function blogJsonLd(notes, { site = SITE_URL, limit = 20 } = {}) {
  const list = Array.isArray(notes) ? notes : [];

  return {
    "@context": SCHEMA_CONTEXT,
    "@type": "Blog",
    name: "猪猪小记",
    url: absoluteUrl("/notes/", site),
    description: NOTES_DESCRIPTION,
    inLanguage: "zh-Hans",
    publisher: organization(site),
    blogPost: list.slice(0, limit).map((note) => blogPostingJsonLd(note, { site, context: false }))
  };
}

export function breadcrumbJsonLd(items, { site = SITE_URL } = {}) {
  return {
    "@context": SCHEMA_CONTEXT,
    "@type": "BreadcrumbList",
    itemListElement: (Array.isArray(items) ? items : []).map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      item: absoluteUrl(item.path, site)
    }))
  };
}

// Safe to inline inside <script type="application/ld+json">: a `<` in note
// text could otherwise close the script element.
export function serializeJsonLd(data) {
  return JSON.stringify(data).replace(/</g, "\\u003c");
}
